services:
  database:
    image: "postgres:latest"
    restart: "unless-stopped"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recall
    volumes:
      - pgdata:/var/lib/postgresql/recalldata

volumes:
  pgdata:
